### ISSUE TITLE
[Python] Cargo Zenoh Flow

### ISSUE THREAD

**Issue by J-Loudet** [eclipse-zenoh/zenoh-flow#111]
# Summary

Cargo Zenoh Flow is able to generate template code for nodes written in Rust. It would be nice to have the same functionality for nodes written in Python.

# Intended outcome

Cargo Zenoh Flow is able to generate template code for nodes written in Python: `cargo zenoh-flow new foo --kind operator --language python`.

# Steps

TBD.

**Comment by gabrik** [comment]
Implemented in https://github.com/eclipse-zenoh/zenoh-flow/pull/110
