### ISSUE TITLE
[C++] Cargo Zenoh Flow

### ISSUE THREAD

**Issue by J-Loudet** [eclipse-zenoh/zenoh-flow#112]
# Summary

Cargo Zenoh Flow is able to generate template code for nodes written in Rust. It would be nice to have the same functionality for nodes written in C++.

# Intended outcome

Cargo Zenoh Flow is able to generate template code for nodes written in Python: `cargo zenoh-flow new foo --kind operator --language c++`.

# Steps

TBD.

**Comment by gabrik** [comment]
Implemented in #110
