### ISSUE TITLE
Dissociate the `setup` and `run` phases when starting a node

### ISSUE THREAD

**Issue by J-Loudet** [eclipse-zenoh/zenoh-flow#124]
### Describe the feature

Dissociating both phases is a first step towards being able to "pause" a running data flow.

For now, when nodes are stopped, the only way to restart them is to call `setup` again. Calling `setup` regenerates (and clears) their internal state.

By dissociating the `setup` from the `run`, we would be able to choose to either resume (calling `run` & keeping the internal state) or reset (calling `setup` + `run`) the execution of a node.

**Comment by gabrik** [comment]
Done in https://github.com/ZettaScaleLabs/zenoh-flow/pull/8
