### ISSUE TITLE
Failure during build

### ISSUE THREAD

**Issue by pgraff** [eclipse-zenoh/zenoh-flow#5]
I just cloned the project and try to build it. I got the following error:
```
   Compiling futures v0.3.16
error: failed to run custom build command for `opencv v0.53.1`

Caused by:
  process didn't exit successfully: `/Users/pettergraff/zenoh/zenoh-flow/target/release/build/opencv-74dd975614494abf/build-script-build` (signal: 6, SIGABRT: process abort signal)
  --- stderr
  dyld: Library not loaded: @rpath/libclang.dylib
    Referenced from: /Users/pettergraff/zenoh/zenoh-flow/target/release/build/opencv-74dd975614494abf/build-script-build
    Reason: image not found
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I'm running on a Mac with the M1 processor. Also, I'm using cargo version 1.52.0, Rustc 1.52.1.

Any ideas?

**Comment by JEnoch** [comment]
I think the problem is the same than detailed in point 6 [here](https://github.com/twistedfall/opencv-rust#troubleshooting).
Please try to set the `DYLD_FALLBACK_LIBRARY_PATH` environment variable as explained in here.
