### ISSUE TITLE
Failed to compile from sources

### ISSUE THREAD

**Issue by haianos** [eclipse-zenoh/zenoh-flow#7]
After resolving some missing dependencies (clang-sys), I hit the following compilation error (zenoh-dependent):

```
   Compiling zenoh-plugin-trait v0.1.0-dev (https://github.com/eclipse-zenoh/zenoh.git?branch=master#70182ad7)
error[E0433]: failed to resolve: use of undeclared type `SharedMemoryAuthenticator`
   --> /home/enea/.cargo/git/checkouts/zenoh-cc237f2570fab813/70182ad/zenoh/src/net/transport/unicast/manager.rs:194:25
    |
194 |                 .insert(SharedMemoryAuthenticator::new().into());
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type `SharedMemoryAuthenticator`
   ```

cargo version `1.54`, rustc version `1.54`

**Comment by Mallets** [comment]
This is due to a missing conditional compilation check. I'm gonna fix it soon.

**Comment by Mallets** [comment]
Done! I've pushed the fix in the zenoh repository from which zenoh-flow depends on.
It should be enough to run `cargo update` in zenoh-flow to refresh the pointer to zenoh to the most recent commit.

**Comment by haianos** [comment]
It worked, thanks!
